"""empty message

Revision ID: 0aa765eaf89a
Revises: 
Create Date: 2019-10-15 16:44:35.130864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0aa765eaf89a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reward')
    op.add_column('PROLIFIC_TASK', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PROLIFIC_TASK', 'title')
    op.create_table('Reward',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Reward_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('w_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points_earned', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_bonus', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_reward', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['w_id'], ['Worker.id'], name='Reward_w_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Reward_pkey')
    )
    # ### end Alembic commands ###
