"""empty message

Revision ID: 27ffaeaf0a7a
Revises: 502d2b034180
Create Date: 2020-04-08 08:49:16.102013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ffaeaf0a7a'
down_revision = '502d2b034180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SELF_EFFICACY', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SELF_EFFICACY', 'timestamp')
    # ### end Alembic commands ###
