"""empty message

Revision ID: 502d2b034180
Revises: bff5ee2582f6
Create Date: 2020-04-08 08:44:53.338384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d2b034180'
down_revision = 'bff5ee2582f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ENJOYMENT', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ENJOYMENT', 'timestamp')
    # ### end Alembic commands ###
